### ISSUE TITLE
How can I use Authentication Code Grant Flow type?

### ISSUE THREAD

**Issue by cyantarek** [go2s/o2s#1]

**Comment by wongoo** [comment]
@cyantarek please provide more details，eg background, scenario, code sample, etc

**Comment by cyantarek** [comment]
In your README.md file, you have shown:

01. grant_type=client_credentials
02. grant_type=password
03. grant_type=refresh_token
04. grant_type=implicit

But the one more appropriate is the grant_type=authorization_code

But you didn't mention how to do it

**Comment by wongoo** [comment]
@cyantarek Yes! the authorization_code is not shown in readme, because it is not required in our production now. But the authorization_code is supported by default.  

The authorization Code Flow can refer to https://tools.ietf.org/html/rfc6749#section-4.1. If u have time to submit a PR about it, that would be very nice.  And would u like to join to maintain this library together?
